[project]
name = "inventory_sourcing"
version = "0.1.0"
description = "inventory-sourcing using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.201.1,<1.0.0"
]

[project.scripts]
inventory_sourcing = "inventory_sourcing.main:run"
run_crew = "inventory_sourcing.main:run"
train = "inventory_sourcing.main:train"
replay = "inventory_sourcing.main:replay"
test = "inventory_sourcing.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
